name: regularized-linear-regression
channels:  
    - conda-forge
dependencies:  
    - python=3.8.18
    - numpy=1.24.3
    - pandas=2.0.3
    - Matplotlib=3.7.2
    - scikit-learn=1.3.2
    - seaborn=0.9.0
    - jupyter_core=5.7.2
    - ipython=8.12.2
    - ipykernel=6.29.5
    - jupyter_client=8.6.0
    - nbconvert=7.16.4
    - ipywidgets=8.1.2
    - nbformat=5.10.4
    - traitlets=5.14.3
    - jupyter_server=2.14.1
    - jupyterlab=4.2.5
    - nbclient=0.8.0
    - jupyterlab-git=0.50.1
    - jupyterlab-variableinspector=3.2.4
    - jupyterlab_code_formatter=3.0.2
    - markdown-it-py=3.0.0
    - nbconvert-core=7.16.4
    - nbconvert-pandoc =7.16.4
    - nbdime=4.0.2
    - folium=0.18.0
    # - nbpreview